### PR TITLE
Fix inconsistency in Roses' Erect metadata

### PR DESCRIPTION
**Pull request by AbnormalPoof**
kawaisprite -> Kawai Sprite

### CODE REVIEW

**Review by JVNpixels — APPROVED** [review]

**Comment by Cartridge-Man** [comment]
Literally unplayable without this change

**Comment by AbnormalPoof** [comment]
Not implemented in 0.5.3.

**Comment by EliteMasterEric** [comment]
Everything in 0.5.3 was pushed back to make way for an urgent hotfix. This is now marked for milestone v0.5.4 (which might not even happen before the pit stop).

**Comment by AbnormalPoof** [comment]
Fair enough!

**Comment by Hundrec** [comment]
Can't recover this one, change was made internally

**Pull request merged**
