### PR TITLE
notes

### PR DESCRIPTION
**Pull request by 7oltan**

### CODE REVIEW

**Comment by moxie-coder** [comment]
is this supposed to optimize the notesplashes?

**Comment by nebulazorua** [comment]
what is this

**Comment by CyndaquilDAC** [comment]
Ingame screenshot?

**Comment by 7oltan** [comment]
So sorry 😭 I literally don't know how to use GitHub I didn't think it was gonna be public lmao

**Comment by 7oltan** [comment]
> is this supposed to optimize the notesplashes?

Yea

**Pull request closed without merging**
