### PR TITLE
Musicians for Sep 12 Pico Update

### PR DESCRIPTION
**Pull request by kawa-kitsuragi**

### CODE REVIEW

**Comment by anysad** [comment]
erm, how does bro know this information 🤓

**Comment by tposejank** [comment]
> erm, how does bro know this information 🤓

What

**Comment by anysad** [comment]
what

**Comment by JustJasonLol** [comment]
what

**Comment by JVNpixels** [comment]
she works for fnf bro 💀😭🙏

**Comment by tposejank** [comment]
Okay

**Comment by anysad** [comment]
Okay

**Pull request closed without merging**
