### PR TITLE
Fix Pico death spritesheet

### PR DESCRIPTION
**Pull request by doggogit**
With `Free Texture Packer`, there is a built-in PNG optimizer, called `tinyPNG`.

When a spritesheet is too large and is ran through `tinyPNG`, it'll overcompensate and transparency will be lost, leading to a tint appearing across the entire sprite.

I re-exported the sheet using `Funkin Packer` (a fork of `Free Texture Packer` by Ne_eo), but this time, running it through only `oxipng`. 

Even at `oxipng`'s highest optimization flag level, no tint appears.

### CODE REVIEW

**Comment by usb-port-2** [comment]
Funkin Packer my beloved

**Comment by doggogit** [comment]
Oh my God, I'm so stupid..

I accidentally deleted the fork by accident, Jesus Christ.

@EliteMasterEric has this been merged internally or do I need to re-open?

**Comment by doggogit** [comment]
Reopened in #50. God.

**Comment by EliteMasterEric** [comment]
Oh yeah this got merged internally.

**Pull request closed without merging**
