### PR TITLE
[OVERHAUL] Assets re-exported and optimized

### PR DESCRIPTION
**Pull request by doggogit**
## Introduction
As the title of the PR says, this aims to re-export and optimize all assets found within this repository.

This will be marked as a **draft**, as I'll do each folder separately.

I am still debating whether or not to "compress" all the sound files found within the repository.

If anyone has any ideas of how to optimize further or have another method, please, feel free to chip in.

## Folders done:
- [ ] `preload`
- [ ] `shared`
- [x] `week1`
- [ ] `week2`
- [ ] `week3`
- [ ] `week4`
- [ ] `week5`
- [ ] `week6`
- [ ] `week7`
- [ ] `weekend1`

## Tools used:
- [`dev` branch of Funkin' Packer](https://github.com/NeeEoo/Funkin-Packer/tree/dev)
- [oxipng](https://github.com/shssoichiro/oxipng)

### CODE REVIEW

**Comment by M7theguy** [comment]
This has nothing to do with this PR but could you maybe optimize this Sticker please?
gfSticker3

**Comment by doggogit** [comment]
> This has nothing to do with this PR but could you maybe optimize this Sticker please? gfSticker3

Here:
gfSticker3

**Comment by M7theguy** [comment]
Thanks!!

**Comment by doggogit** [comment]
Unmarking `preload` as complete.

Need some things to fix.

**Comment by doggogit** [comment]
Re-opening things in a bit.

**Pull request closed without merging**
