### PR TITLE
fix + optimize InverseDots shader

### PR DESCRIPTION
**Pull request by cyn0x8**
fixed grid logic (in turn fixing an implicit cast error) and made some optimizations

now it looks identical to Flash/Animate !!

image

image

in Animate for reference:

image

### CODE REVIEW

**Comment by cyn0x8** [comment]
hmmmm this only seems to be true when the camera zoom is >1 though

image

image

image

the shader needs to somehow be applied "relative to" (idk a better word lol) the camera rather than the sprite bitmap so that its pixel perfect onscreen... but thats outside the scope of this pr

**Comment by Burgerballs** [comment]
> hmmmm this only seems to be true when the camera zoom is >1 though
> 
> image
> 
> image
> 
> image
> 
> the shader needs to somehow be applied "relative to" (idk a better word lol) the camera rather than the sprite bitmap so that its pixel perfect onscreen... but thats outside the scope of this pr

Try adding some dot size multiplier that is set to the 1 divided by the cam zoom, that should probably work

**Comment by JustKolosaki** [comment]
> hmmmm this only seems to be true when the camera zoom is >1 though
> 
> image
> 
> image
> 
> image
> 
> the shader needs to somehow be applied "relative to" (idk a better word lol) the camera rather than the sprite bitmap so that its pixel perfect onscreen... but thats outside the scope of this pr

I'll look into making a separate camera for every object and then applying the shader to the aforementioned camera, either that or having an external variable that controls the sizes of dots would suffice. Nonetheless great work!!!

**Comment by cyn0x8** [comment]
> I'll look into making a separate camera for every object and then applying the shader to the aforementioned camera, either that or having an external variable that controls the sizes of dots would suffice.

i think either a uniform or applying the shader directly during rendering would be best

having lots of cameras is expensive!! i know from experience

**Comment by JustKolosaki** [comment]
> i think either a uniform or applying the shader directly during rendering would be best
> 
> having lots of cameras is expensive!! i know from experience

One camera used for the current object and then repositioning the camera per object change should be enough lol

**Comment by biomseed** [comment]
> the shader needs to somehow be applied "relative to" (idk a better word lol) the camera rather than the sprite bitmap so that its pixel perfect onscreen... but thats outside the scope of this pr

I've done something like that in a source engine shader, where it's hard to do there. It can be done if you have the right parameters, which they do.

**Pull request merged**
