### PR TITLE
[BUGFIX] Use correct album art for Satin Panties and Eggnog Erect

### PR DESCRIPTION
**Pull request by doggogit**
Simple PR, title says it all :]

### CODE REVIEW

**Comment by Hundrec** [comment]
Unfortunately, these two songs belong to another album called "OST Expansion Vol. 1"

Can't wait to see them implement the art!

**Comment by doggogit** [comment]
> Unfortunately, these two songs belong to another album called "OST Expansion Vol. 1"
> 
> Can't wait to see them implement the art!

Oh, yeah, they do actually... Should I close this?

**Comment by Hundrec** [comment]
Yeah, we should wait for them to add the right albums in 0.5.0

**Comment by doggogit** [comment]
Alrighty, closing!

**Pull request closed without merging**
